Fix server settings backup creation (#1806)
The "download conversions headers" caused a SerializationException.

kotlinx.serialization.SerializationException: 'null' is not supported as the value of collection types in ProtoBuf